# Generated by Django 6.0.7 on 2026-07-28 16:57
'''This file is a migration, which means it is a script that tells Django:

'Create these tables in the database with these fields and relationships.'
It does not contain the application logic, but rather describes the structure of the database.


0001_initial.py: instructions for building the database

The 0001_initial.py file is a migration automatically generated by Django from models.py. 
It contains all the operations necessary to physically create the database.

When you run: python manage.py migrate

Django reads this file and executes operations such as:

    creating tables;
    creating primary keys;
    creating foreign keys (ForeignKey);
    creating indexes;
    applying constraints (unique, unique_together, etc.).

0001_initial.py, on the other hand, is used only when it is necessary to create or modify the database structure. 
Once the migration has been applied, the file remains as a historical record of the changes made to the database.'''

# models is used to define field types, migrations is used to create migration operations, 
# deletion contains the rules on what to do when a record is deleted (for example, CASCADE).
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # First migration of the app, it creates the tables from scratch.
    initial = True

    dependencies = [
    ]

    # All operations to be executed on the database
    operations = [
        # Create a new table
        migrations.CreateModel(
            # Table 'Actor'
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # Official name of the actor
                ('canonical_name', models.CharField(max_length=200, unique=True)),
                # The associated country
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                # Actor's motivation
                ('motivation', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('first_seen', models.DateField(blank=True, null=True)),
            ],
            # Used only for the Django admin interface
            options={
                # The plural will be displayed as: Actors
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=100, unique=True)),
                # First observation
                ('first_seen', models.DateField(blank=True, null=True)),
                # Last observation
                ('last_seen', models.DateField(blank=True, null=True)),
                # Description of the campaign
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            # Represents an internet domain
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                # Domain category. For example Malware or Phishing
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                # When the domain was created. Django automatically saves the creation date
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            # TTP stands for Tactics, Techniques, and Procedures, which means the techniques used by attackers
            name='TTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttp_code', models.CharField(max_length=20, unique=True)),
                ('is_generic', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            # Used to store aliases. For example, APT28 can have aliases such as Fancy Bear or Sofacy
            # relationship is many-to-one, meaning that an actor can have multiple aliases, but each alias belongs to one actor.
            name='ActorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200, unique=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='api.actor')),
            ],
            options={
                'verbose_name_plural': 'Actor aliases',
            },
        ),
        migrations.CreateModel(
            # Used to save items classified as false positives.
            name='FalsePositive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # category - type of the object
                ('category', models.CharField(choices=[('actor', 'Actor'), ('domain', 'Domain'), ('ip', 'IP'), ('hash', 'Hash'), ('email', 'Email'), ('ttp', 'TTP'), ('cve', 'CVE'), ('url', 'URL'), ('suspicious_file', 'Suspicious File')], max_length=50)),
                # The actual value. For example 192.168.1.10
                ('value', models.CharField(max_length=500)),
                ('context', models.TextField(blank=True, null=True)),
                # Article it comes from
                ('source_article', models.CharField(blank=True, max_length=500, null=True)),
                # Automatic date of creation
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                # You cannot have two identical records
                'unique_together': {('category', 'value')},
            },
        ),
        migrations.CreateModel(
            # Similar to FalsePositive. Here, however, examples of IOCs (Indicators of Compromise) are saved
            name='IOCExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ip', 'IP'), ('domain', 'Domain'), ('hash', 'Hash'), ('actor', 'Actor'), ('ttp', 'TTP'), ('cve', 'CVE'), ('url', 'URL'), ('suspicious_file', 'Suspicious File')], max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('context', models.TextField(blank=True, null=True)),
                ('source_article', models.CharField(blank=True, max_length=500, null=True)),
                # Represents the reliability level
                ('confidence', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('category', 'value')},
            },
        ),
        migrations.CreateModel(
            # Represents the many-to-many relationship between Campaign and Actor
            # Junction table. A campaign can involve multiple actors. An actor can participate in multiple campaigns
            name='CampaignActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actor')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'actor')},
            },
        ),
        migrations.CreateModel(
            # Represents the many-to-many relationship between Actor and Domain
            # Junction table. An actor can use multiple domains. A domain can be used by multiple actors
            name='ActorDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # How many times that domain was observed associated with that actor
                ('frequency', models.IntegerField(default=1)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.actor')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.domain')),
            ],
            options={
                'unique_together': {('domain', 'actor')},
            },
        ),
        migrations.CreateModel(
            # Represents the many-to-many relationship between Campaign and TTP
            # Junction table. A campaign can involve multiple TTPs. A TTP can be used in multiple campaigns
            name='CampaignTTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campaign')),
                ('ttp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ttp')),
            ],
            options={
                'unique_together': {('campaign', 'ttp')},
            },
        ),
    ]
